stages:
  - build
  - test
  - deploy

# Use a Docker image with Docker pre-installed
image: docker:latest

# Services needed to run Docker
services:
  - docker:dind

variables:
  # Define the Docker image name and tag
  DOCKER_IMAGE: blog-app

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE .
  tags:
    - docker

test:
  stage: test
  script:
    - echo "Running tests"
    # You can run any test command here
  tags:
    - docker

deploy:
  stage: deploy
  script:
    - docker run -d -p 8080:80 $DOCKER_IMAGE
  tags:
    - docker
  only:
    - main
